const DECORATOR_KEY =  {
    CONTROLLER_PATH: Symbol('CONTROLLER_PATH'),
    SK_CONTROLLER_PATH: Symbol('SK_CONTROLLER_PATH'),
    CONTROLLER: Symbol('CONTROLLER'),
    SOCKET: Symbol('SOCKET'),
    PARAM: Symbol('PARAM'),
    ACTION: Symbol('ACTION'),
    METHOD: Symbol('METHOD'),
    ROUTE_PATH: Symbol('ROUTE_PATH'),
    RESPONSE: Symbol('RESPONSE'),
    REQUEST: Symbol('REQUEST'),
    REQUEST_BODY: Symbol('REQUEST_BODY'),
    REQUEST_BODY_OPTIONS: Symbol('REQUEST_BODY_OPTIONS'),
    REQUEST_BODY_TYPE: Symbol('REQUEST_BODY_TYPE'),
    QUERY: Symbol('QUERY'),
    MIDDLEWARE: Symbol('MIDDLEWARE'),
    INTERCEPTOR: Symbol('INTERCEPTOR'),
    BEFORE_INTERCEPTOR: Symbol('BEFORE_INTERCEPTOR'),
    AFTER_INTERCEPTOR: Symbol('AFTER_INTERCEPTOR'),
    FILE_UPLOAD: Symbol('FILE_UPLOAD'),
	SOCKET_INSTANCE: Symbol('SOCKET_INSTANCE'),
	SOCKET_CALLBACK: Symbol('SOCKET_CALLBACK'),
	SOCKET_DATA: Symbol('SOCKET_DATA'),
    SOCKET_BODY: Symbol('SOCKET_BODY'),
    SOCKET_DATA_KEY: Symbol('SOCKET_DATA_KEY')
} as const;

export {
    DECORATOR_KEY
}